stages:
  download:
    cmd: python src/download.py
    deps:
    - src/download.py
    params:
    - download.n_loc
    - download.year
    outs:
    - data/weatherData.csv
  prepare:
    cmd: python src/prepare.py data/weatherData.csv data/groundTruthData.csv
    deps:
    - data/weatherData.csv
    - src/prepare.py
    params:
    - prepare.seed
    outs:
    - data/groundTruthData.csv
  process:
    cmd: python src/process.py data/weatherData.csv data/predictedDataTruth.csv
    deps:
    - data/weatherData.csv
    - src/process.py
    outs:
    - data/predictedDataTruth.csv
  evaluate:
    cmd: python src/evaluate.py data/groundTruthData.csv data/predictedDataTruth.csv
    deps:
    - data/groundTruthData.csv
    - data/predictedDataTruth.csv
    - src/evaluate.py
    outs:
    - data/R2_score.txt
